config:
  target: "http://localhost:3000"
  http:
    timeout: 30000
  phases:
    - duration: 5
      arrivalRate: 20
  processor: "./artillery-processor.js"

scenarios:
  - name: "Submit responses"
    flow:
      - get:
          url: "/api/questions"
          capture:
            - json: "$"
              as: "questionsData"
      - function: "generatePayload"
      - post:
          url: "/api/submit"
          json:
            "{{ payload }}"
