config:
  target: "http://localhost:3000"
  phases:
    - duration: 3
      arrivalRate: 3
  processor: "./artillery-processor.js"  # external JS file
  defaults:
    headers:
      Content-Type: "application/json"

scenarios:
  - flow:
      - get:
          url: "/api/questions"
          capture:
            - json: "$"
              as: "questionsData"
      - function: "buildAnswers"
      - post:
          url: "/api/responses"
          json:
            answers: "{{ answers }}"
            timestamp: "{{ timestamp }}"